---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - add_host:
        hostname : "{{ user }}"
        groups: webserver

- hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
  - name: Adding public key
    copy:
      src: /Users/Weeto/.ssh/id_rsa.pub
      dest: /home/{{ sudo_user }}/.ssh/id_rsa.pub
      owner: "{{ sudo_user }}"
      group: "{{ sudo_user }}"
      mode: 0600