---
- hosts: localhost
  connection: local
  tasks:
    - add_host:
        hostname : "{{ item }}"
        groups: webserver
      loop: "{{ user }}"

- hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
   - name: Stop MySql-server
      action: service name=mysql state=stopped