---
- hosts: localhost
  connection: local
  tasks:
    - add_host:
        hostname : "{{ item }}"
        groups: webserver
      loop: "{{ user }}"

- hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
    - name: Connecting to server
      action: ping

    - name: Set mysql root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{ db_pass | quote}}' vtype='password'
      become: true

    - name: Confirm mysql root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ db_pass | quote}}' vtype='password'
      become: true

    - name: Install database server
      apt: name={{item}}
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb

    - name: Start mysql
      action: service name=mysql state=started

    - name: remove test database
      mysql_db: name=test state=absent

    - name: Create mysql user for database
      mysql_user: user= "{{ db_user }}" host="%" password="{{ db_pass }}" priv=*.*:ALL,GRANT

    - name: Check for anonymous users and remove
      mysql_user: user='' host=$item state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password="{{ db_pass }}"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create a new database with name "{{ db_name }}"
      mysql_db: name='{{ db_name }}' state=present