---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - add_host:
        hostname : "{{ user }}"
        groups: webserver

- hosts: webserver
  become: yes
  become_method: sudo
  tasks:
    - name: Set mysql root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{ db_pass | quote}}' vtype='password'
      become: true

    - name: Confirm mysql root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ db_pass | quote}}' vtype='password'
      become: true

    - name: Install mysql-server
      apt: pkg=mysql-server state=present

    - name: Install mysql-client
      apt: pkg=mysql-client state=present

    - name: Install python-mysqldb
      apt: pkg=python-mysqldb state=present

    - name: Start mysql
      action: service name=mysql state=started

    - name: remove test database
      mysql_db: name=test state=absent

    - name: Create mysql user for database
      mysql_user: user= "{{ db_user }}" host="%" password="{{ db_pass }}" priv=*.*:ALL,GRANT

    - name: Check for anonymous users and remove
      mysql_user: user='' host=$item state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password="{{ db_pass }}"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create a new database with name "{{ db_name }}"
      mysql_db: name='{{ db_name }}' state=present