---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - add_host:
        hostname : "{{ item }}"
        groups: webserver
      loop: "{{ user }}"

- hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
    - name: install php packages
      apt: pkg={{ item }} state=present
      with_items:
      - php-common
      - php-curl
      - php-fpm
      - php-imagick
      - php-mbstring
      - php-memcache
      - php-memcached
      - php-mysql
      - php7.0-cli
      - php7.0-common
      - php7.0-curl
      - php7.0-fpm
      - php7.0-json
      - php7.0-mbstring
      - php7.0-mysql
      - php7.0-opcache
      - php7.0-readline
      - php7.0-xml
      - php7.0-zip
      - php7.0-gd