---
- hosts: localhost
  connection: local
  tasks:
    - add_host:
        hostname : "{{ item }}"
        groups: webserver
      loop: "{{ user }}"

- hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
  - name: Connecting to server
    action: ping
  - name: Ensure apt cache is up to date
    apt: update_cache=yes
  - name: Ensure PostgreSql packages are installed
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: webserver
  gather_facts: false
  become_method: sudo

  vars:
    ansible_ssh_pipelining: true
    ansible_become: true
    ansible_become_user: postgres
    allow_world_readable_tmpfiles: true
    dbname: "{{ db_name }}"
    dbuser: "{{ db_user }}"
    dbpassword: "{{ db_pass }}"

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db='{{db_name}}' name='{{db_user}}' password='{{db_pass}}' priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name='{{db_user}}' role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure no other user can access the database
    postgresql_privs: db='{{db_name}}' role=PUBLIC type=database priv=ALL state=absent
